package ai.agent.learning.lesson;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Lesson3RunSimple - TodoManager 单元测试
 */
class Lesson3TodoManagerTest {

    private Lesson3RunSimple.TodoManager todoManager;

    @BeforeEach
    void setUp() {
        todoManager = new Lesson3RunSimple.TodoManager();
    }

    @Test
    @DisplayName("测试初始状态 - 无todos")
    void testEmptyState() {
        String result = todoManager.render();
        assertEquals("No todos.", result);
        assertFalse(todoManager.hasOpenItems());
    }

    @Test
    @DisplayName("测试添加单个待办项")
    void testAddSingleItem() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "测试任务", "status", "pending")
        );

        String result = todoManager.update(items);

        assertTrue(result.contains("[ ] #1: 测试任务"));
        assertTrue(result.contains("(0/1 completed)"));
        assertTrue(todoManager.hasOpenItems());
    }

    @Test
    @DisplayName("测试进行中状态")
    void testInProgressItem() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "进行中任务", "status", "in_progress")
        );

        String result = todoManager.update(items);

        assertTrue(result.contains("[>] #1: 进行中任务"));
        assertTrue(todoManager.hasOpenItems());
    }

    @Test
    @DisplayName("测试已完成状态")
    void testCompletedItem() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "已完成任务", "status", "completed")
        );

        String result = todoManager.update(items);

        assertTrue(result.contains("[x] #1: 已完成任务"));
        assertTrue(result.contains("(1/1 completed)"));
        assertFalse(todoManager.hasOpenItems());
    }

    @Test
    @DisplayName("测试多个待办项")
    void testMultipleItems() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "任务1", "status", "completed"),
                Map.of("id", "2", "text", "任务2", "status", "in_progress"),
                Map.of("id", "3", "text", "任务3", "status", "pending")
        );

        String result = todoManager.update(items);

        assertTrue(result.contains("[x] #1: 任务1"));
        assertTrue(result.contains("[>] #2: 任务2"));
        assertTrue(result.contains("[ ] #3: 任务3"));
        assertTrue(result.contains("(1/3 completed)"));
    }

    @Test
    @DisplayName("测试无效状态 - 应抛出异常")
    void testInvalidStatus() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "任务", "status", "invalid")
        );

        assertThrows(IllegalArgumentException.class, () -> todoManager.update(items));
    }

    @Test
    @DisplayName("测试空文本 - 应抛出异常")
    void testEmptyText() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "", "status", "pending")
        );

        assertThrows(IllegalArgumentException.class, () -> todoManager.update(items));
    }

    @Test
    @DisplayName("测试多个进行中任务 - 应抛出异常")
    void testMultipleInProgress() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "任务1", "status", "in_progress"),
                Map.of("id", "2", "text", "任务2", "status", "in_progress")
        );

        assertThrows(IllegalArgumentException.class, () -> todoManager.update(items));
    }

    @Test
    @DisplayName("测试超过20个待办项 - 应抛出异常")
    void testMaxItemsExceeded() {
        List<Map<String, Object>> items = new java.util.ArrayList<>();
        for (int i = 1; i <= 21; i++) {
            items.add(Map.of("id", String.valueOf(i), "text", "任务" + i, "status", "pending"));
        }

        assertThrows(IllegalArgumentException.class, () -> todoManager.update(items));
    }

    @Test
    @DisplayName("测试自动生成ID")
    void testAutoGeneratedId() {
        List<Map<String, Object>> items = List.of(
                Map.of("text", "无ID任务", "status", "pending")
        );

        String result = todoManager.update(items);
        assertTrue(result.contains("#1: 无ID任务"));
    }

    @Test
    @DisplayName("测试状态不区分大小写")
    void testCaseInsensitiveStatus() {
        List<Map<String, Object>> items = List.of(
                Map.of("id", "1", "text", "任务", "status", "IN_PROGRESS")
        );

        String result = todoManager.update(items);
        assertTrue(result.contains("[>] #1: 任务"));
    }
}
